services:
  backend:  
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=manager.py
      - FLASK_ENV=development
    command: >
      sh -c "
        python manager.py &&
        flask db init &&
        flask db migrate -m 'Initial migration' &&
        flask db upgrade
      "
    ports:
      - "8001:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:8.0.11
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33067:3306"

volumes:
  dbdata:
